/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: bde3be7c6177c43fa659e789244c9642)
interface __BaseEnv_Env {
	OCR_RATE_LIMITER: RateLimit;
	ASSETS: Fetcher;
	GEMINI_MODEL: "gemini-3-flash-preview";
	GEMINI_API_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "GEMINI_MODEL" | "GEMINI_API_KEY">> {}
}
